language: php
php:
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer selfupdate
    - composer install --prefer-source

script: ./vendor/bin/phpunit

sudo: false
