language: php
php:
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer selfupdate
    - composer install --prefer-source
    - mkdir -p build/logs

script: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/coveralls -v; fi;'

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
