#app:
#    resource: "@AppBundle/Controller/DefaultController.php"
#    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type: annotation

bundle:
    resource: "@EkreativeRedmineLoginBundle/Resources/config/routing.yml"
